on:
  # schedule:
    # - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: latest
      - run: node russian-roulette.ts
        env:
          DISCUIT_MOD_PASSWORD: ${{ secrets.DISCUIT_MOD_PASSWORD }}
