on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun russian-roulette.ts
        env:
          DISCUIT_MOD_PASSWORD: ${{ secrets.DISCUIT_MOD_PASSWORD }}
